language: python

services:
  - docker

before_install:
  - docker pull mysql/mysql-server:latest
  - docker run --name=mysql1 --restart on-failure -d mysql/mysql-server:latest

script:
  -   pytest -q tests/test_notebooks.py 
  -   pytest --cov tests
  -   coverage run tests/test_notebooks.py 
