version: '3.3'

services:
    db:
        restart: always
        build: .
        environment:
            - MYSQL_DATABASE=123
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=1234
            - MYSQL_ROOT_PASSWORD=1234
       
